<a href="https://colab.research.google.com/github/Angy-face/Esan-Coding-SS2/blob/main/Course2Topic1Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = 'https://drive.google.com/uc?id=18zsxFId1FaUI1RvfkAex6ZoNpToP8GoT'>

---

# ผู้บรรยาย: ผู้ช่วยศาสตราจารย์ ดร. วีระชัย สาระคร
## สาขาวิชาคณิตศาสตร์ คณะวิทยาศาสตร์ มหาวิทยาลัยขอนแก่น

---

# Topic 1: Basic Python Programming for Data Scientists

# 1.1 แนะนำภาษาไพทอน

ดูที่

https://drive.google.com/file/d/1Oqcn7GAB5M91pKNKSh4OxYpvwf6H44DF/view?usp=sharing

(หรือ https://powerclass.org/wp-content/uploads/2023/11/Course2Topic1_1-1.pdf)

In [1]:
print("Hello E-sarn Thailand Coding & AI Academy.")

Hello E-sarn Thailand Coding & AI Academy.


# 1.2 การตั้งชื่อตัวแปรและประเภทของข้อมูลในภาษาไพทอน

## 1.2.1 การตั้งชื่อตัวแปร
**กฎการตั้งชื่อตัวแปรในภาษาไพทอน**
1. ชื่อตัวแปรควรขึ้นต้นด้วยอักษรภาษาอังกฤษ
2. ชื่อตัวแปรนอกจากจะประกอบด้วยตัวอักษรภาษาอังกฤษแล้วยังสามารถประกอบด้วยตัวเลขหรืออักขระพิเศษ `_` โดยที่ไม่มีช่องว่าง
3. ตัวอักษรภาษาอังกฤษตัวเล็กและใหญ่ในชื่อตัวแปรจะให้ความหมายแตกต่างกัน (case-sensitive)
4. ควรตั้งชื่อตัวแปรให้เหมาะสมและง่ายต่อการจดจำ
5. ชื่อตัวแปรต้องไม่ซ้ำกับคำสงวนในภาษาไพทอน (Reserved word, Keyword) เช่น ชื่อคำสั่ง ชื่อฟังก์ชัน ที่มีอยู่ในภาษาไพทอน ตัวอย่างคำสำคัญในภาษาไพทอน ได้แก่

        False      class      finally    is         return
        None       continue   for        lambda     try
        True       def        from       nonlocal   while
        and        del        global     not        with
        as         elif       if         or         yield
        assert     else       import     pass       break
        except     in         raise

## 1.2.2 การกำหนดค่าตัวแปร
ภาษาไพทอนจะใช้เครื่องหมาย = ในการกำหนดค่าให้กับตัวแปร

**รูปแบบการกำหนดค่าให้กับตัวแปรเป็นดังนี้**
```
ตัวแปร = ค่าของตัวแปร
```

**ตัวอย่าง 1.2.1**
ตัวอย่างการตั้งชื่อตัวแปรที่ถูกต้องเป็นดังนี้

In [2]:
Weight=69

In [3]:
print(Weight)

69


In [4]:
Score=98
year = 2023
a1=1
A_1=2.5
Esarn_coders=1000


In [5]:
print(year)
print(a1)
print(Esarn_coders)

2023
1
1000


**ตัวอย่าง 1.2.2**
ตัวอย่างการตั้งชื่อตัวแปรที่ไม่ได้เป็นตามข้อกำหนดเป็นดังนี้

In [6]:
a=-1

In [7]:
C1= 10

In [8]:
da=0.

In [9]:
fo=200

In [10]:
fo = -1000

## 1.2.3 โครงสร้างข้อมูลของภาษาไพทอน (Data structures of Python language)
โครงสร้างข้อมูลของภาษาไพทอนสรุปได้ดังแผนภาพต่อไปนี้
<img src = 'https://drive.google.com/uc?id=1I5fNgjMzDKaUyxCZ0nV6qoC9UBtusr_y' alt = 'แผนภาพแสดงโครงสร้างทางข้อมูลของภาษาไพทอน' width ='800px'>

### 1. ข้อมูลแบบพื้นฐาน(Primitive)

**1.1 ตัวแปรประเภทจำนวนเต็ม (Integer Variables)** เป็นตัวแปรที่มีค่าเป็นจำนวนเต็ม การป้อนค่าตัวเลขจะต้องไม่มีจุด(.)หรือตัวเลขหลังจุดทศนิยม ตัวอย่างเช่น `x = 10`, `count = 5`

**1.2 ตัวแปรประเภททศนิยม (Float Variables)** เป็นตัวแปรที่มีค่าเป็นจำนวนจริงและจัดเก็บในรูปทศนิยมจุดลอย(floating point) เช่น `pi = 3.14`, `average = 5.75`

**1.3 ตัวแปรประเภทสตริง (String Variables)หรือตัวแปรสายอักขระ** เป็นตัวแปรที่เก็บข้อมูลในรูปแบบข้อความหรือกลุ่มของอักขระ ซึ่งกลุ่มของอักขระนี้ได้แก่ ตัวอักษร ตัวเลข สัญลักษณ์ต่างๆ ซึ่งกลุ่มอักขระเหล่านี้จะต้องอยู่ภายใต้เครื่องหมาย `'  '` หรือ `"    "` เช่น `name = "John"`, `message = 'Hello, World!'`

**1.4 ตัวแปรประเภทบูลีน (Boolean Variables) หรือตัวแปรตรรกศาสตร์** เป็นตัวแปรที่จะมีค่าของตัวแปรเป็นจริง(True)หรือเท็จ(False)เท่านั้น เช่น `is_valid = True`, `has_permission = False`

### 2. ข้อมูลแบบซับซ้อน(Non-Primitive)
ข้อมูลประเภทนี้แบ่งเป็น 2 ชนิดได้แก่

**2.1 ข้อมูลแบบซับซ้อนที่กำหนดไว้แล้ว(Built-in)** ได้แก่

**2.1.1 ลิสต์ (List Variables)**
   เป็นตัวแปรที่เก็บค่าของข้อมูลประเภทต่างๆหลายๆ ค่าไว้ด้วยกันได้  เช่น `numbers = [1, 2, 3, 4, 5]`, `names = ['Alice', 'Bob', 'Charlie']`

**2.1.2 ทูเพิล (Tuple Variables)**
   เป็นตัวแปรประเภทลิสต์ประเภทหนึ่งที่กำหนดขึ้นมาแล้วไม่สามารถเปลี่ยนแปลงค่าในภายหลังได้ เช่น `coordinates = (3, 4)`, `colors = ('red', 'green', 'blue')`

**2.1.3 เซต (Set Variables)**
   เป็นตัวแปรที่เก็บข้อมูลในรูปแบบเซต(set) ซึ่งสมาชิกของข้อมูลไม่ซ้ำกัน เช่น `unique_numbers = {1, 2, 3, 4, 5}`, `unique_colors = {'red', 'green', 'blue'}`

**2.1.4 ดิกชันนารี (Dictionary Variables)**
   เป็นตัวแปรที่เก็บข้อมูลในรูปแบบดิกชันนารี (dictionary) ที่มีโครงสร้างคีย์-ค่า (key-value) เช่น `person = {'name': 'John', 'age': 30, 'city': 'New York'}`

**2.2 ข้อมูลแบบซับซ้อนที่กำหนดเอง (User-defined)** ได้แก่

**2.2.1 สแต็ก (Stack)**
เป็นโครงสร้างข้อมูลที่มีลักษณะ Last-In-First-Out (LIFO) กล่าวคือ ข้อมูลที่ถูกเพิ่มล่าสุดจะถูกนำออกไปใช้ก่อน

**2.2.2 คิว (Queue)**
เป็นโครงสร้างข้อมูลที่มีลักษณะ First-In-First-Out (FIFO) กล่าวคือ ข้อมูลที่ถูกเพิ่มอันดับแรกสุดจะถูกนำออกมาใช้ก่อน

**2.2.3 ต้นไม้ (Tree)**
เป็นโครงสร้างข้อมูลที่มีจุดยอด(หรือโหนด)และเส้น(การเชื่อมต่อระหว่างโหนด) โหนดที่อยู่บนสุดจะเรียกว่าราก(root)

**2.2.4 กราฟ (Graph)**
เป็นโครงสร้างข้อมูลที่มีโหนดและเส้นเชื่อมต่อระหว่างโหนด โหนดที่เชื่อมโยงกันเรียกว่า Vertex

**ตัวอย่าง 1.2.3** จงสร้างตัวแปรสำหรับเก็บค่าข้อมูลในแต่ละข้อต่อไปนี้
1. จำนวนผู้ลงทะเบียนเข้าร่วมโครงการ E-sarn Thailand coding & AI จำนวน 1000 คน
2. ค่าที่เกิดจากการปัดเศษ 0.17468 ให้มีจำนวนตำแหน่งทศนิยม 4 ตำแหน่ง
3. ตัวแปรแบบสตริงที่เก็บข้อความ Python Language
4. ค่าของตัวแปร T1 และ T2 ที่มีค่าความจริงที่เป็นเท็จและจริง ตามลำดับ
5. ค่าคะแนนของผู้ร่วมโครงการฯ E-sarn Thailand coding & AI จากกิจกรรม Codecombat จำนวน 5 คนได้แก่ 29.62, 29.5, 29.37,29
6. ข้อมูลยี่ห้อรถยนต์ ได้แก่ toyota, handa, isuzu, mazda
7. พิกัดของจุดมุมของรูปสามเหลี่ยมในระบบพิกัดฉากซึ่งได้แก่ (0,0), (0,1), (1,0) โดยที่ไม่สามารถเปลี่ยนแปลงพิกัดนี้ได้
8. เซตของรายชื่อภาษาโปรแกรมได้แก่ python, javascript, c, swift, ruby

In [11]:
esancoder = 1000
floa =  0.1747
string = "Python Langguage"
T1 , T2 = False ,True
score = [29.62, 29.5, 29.37,29]
car_brand = ['toyota', 'handa', 'isuzu', 'mazda']
coordinate = ( (0,0), (0,1), (1,0) )
com_lang = {'python', 'javascript', 'c', 'swift', 'ruby'}

In [12]:
# ข้อ 1
numEsarnCoders = 1000

In [13]:
# 2
a=0.1747

In [14]:
# 3
s1='Python Language'
s2="Python Language"

In [15]:
# 4
T1=False
T2=True

In [16]:
#5
Score=[29.62,29.5,29.37,29]

In [17]:
#6
Car_Brands=['toyota','honda','isuzu','mazda']

In [18]:
#7
coor1=(0,0)
coor2=(0,1)
coor3=(1,0)

In [19]:
#8
listprog={'python','javascript','c','ruby','swift'}

## 1.2.4 การตรวจสอบประเภทของตัวแปร
ผู้ใช้งานสามารถตรวจสอบประเภทของตัวแปรหรือข้อมูลที่ต้องการ โดยใช้คำสั่ง `type` รูปแบบคำสั่งเบื้องต้นเป็นดังนี้
```
type(var)
```
เมื่อ ``var`` เป็นตัวแปรหรือข้อมูลที่ต้องการ

**ตัวอย่าง 1.2.4** จงตรวจสอบประเภทของตัวแปรในตัวอย่าง 1.2.3

In [20]:
type(numEsarnCoders)

int

In [21]:
type(s2)

str

In [22]:
type(T1)

bool

In [23]:
type(listprog)

set

# 1.3. คำสั่งการรับข้อมูลเข้าและแสดงผล
## 1.3.1 การรับข้อมูลเข้า
สำหรับภาษาไพทอน การรับข้อมูลเข้าผ่านทางแป้นพิมพ์จะใช้คำสั่ง `input` โดยมีรูปแบบการใช้งานดังนี้
```
x = input([prompt])
```
เมื่อ `x` เป็นตัวแปรทีจะรับค่าข้อมูลซึ่งจะเป็นตัวแปรแบบสายอักขระ `prompt`เป็นข้อความสายอักขระที่ต้องการแสดงบนหน้าจอซึ่งข้อความนี้จะมีหรือไม่มีก็ได้(optional)
กรณีที่ มีรับค่าข้อมูลหลายค่าที่ข้อมูลแต่ละค่าคั่นด้วยช่องว่างให้คั่นระหว่างชื่อตัวแปรด้วย $,$ ตัวอย่างเช่น รับค่า 3 ค่าพร้อมกัน ดังนี้
```
x1,x2,x3 = input([prompt]).split()
```
กรณีต้องการรับค่าข้อมูลและจัดเก็บให้เป็นจำนวนเต็ม จะใช้คำสั่งดังนี้
```
x = int(input([prompt]))
```
กรณีต้องการรับค่าข้อมูลและจัดเก็บให้เป็นจำนวนจริง จะใช้คำสั่งดังนี้
```
x = float(input([prompt]))
```

**ตัวอย่าง 1.3.1** จงบอกคำสั่งในการป้อนค่าข้อมูลในแต่ละข้อต่อไปนี้
1. รับค่าชื่อจังหวัดจากแป้นพิมพ์และเก็บไว้ในตัวแปร `prov1` โดยให้แสดงข้อความ "กรุณาป้อนชื่อจังหวัดที่เกิด:" ก่อนการรับค่า
2. รับค่าชื่อผลไม้ 3 ประเภทจากแป้นพิมพ์และเก็บไว้ในตัวแปร `fruit1`,`fruit2`,`fruit3` โดยให้แสดงข้อความ "กรุณาป้อนชื่อผลไม้ 3 ประเภท" ก่อนการรับค่า
3. รับค่าจำนวนเฉพาะจากแป้นพิมพ์และเก็บไว้ในตัวแปร `prime1` โดยให้แสดงข้อความ "Input your prime number" ก่อนการรับค่า
4. รับค่าประมาณของ $\pi$ ที่แสดงถึงทศนิยมตำแหน่งที่ 4 จากแป้นพิมพ์และเก็บไว้ในตัวแปร `pii` โดยให้แสดงข้อความ "Input the approximation of pi with 4 decimal places" ก่อนการรับค่า

In [24]:
prov1=input('กรุณาป้อนชื่อจังหวัดที่เกิด:')

กรุณาป้อนชื่อจังหวัดที่เกิด:111


In [25]:
fruit1,fruit2,fruit3=input('กรุณาป้อนชื่อผลไม้ 3 ประเภท').split()

กรุณาป้อนชื่อผลไม้ 3 ประเภท11111


ValueError: not enough values to unpack (expected 3, got 1)

In [ ]:
prime1=int(input('Input your prime number'))

In [ ]:
pii=float(input('input the approximation of pi with 4 decimal places'))

## 1.3.2 การแสดงผล
สำหรับภาษาไพทอนจะใช้คำสั่ง `print` ในการแสดงผลทางจอภาพ ซึ่งมีรูปแบบการใช้งานดังนี้
```
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
```
`value` เป็นค่าตัวแปรหรือสายอักขระที่ต้องการแสดงผล

`sep` เป็นสายอักขระที่ต้องการแทรกระหว่างค่า โดยการตั้งค่าเริ่มต้นของไพทอน จะเป็นช่องว่าง 1 ช่อง

`end` เป็นสายอักขระที่เป็นค่าสุดท้าย โดยการตั้งค่าเริ่มต้นของไพทอน จะเป็นการขึ้นบรรทัดใหม่ หรือ`\n`

`file` เป็นชื่อไฟล์ที่ต้องการเก็บการแสดงผล ซึ่งถ้า `file=sys.stdout`หรือไม่มีการระบุตัวเลือกนี้ จะเป็นการแสดงผ่านทางหน้าจอ แต่ถ้าระบุเป็นชื่อไฟล์อื่นก็สามารถทำได้ ซึ่งประเภทของไฟล์อาจจะเป็น .txt, .cvs เป็นต้น

`flush`เป็นตัวกำหนดการล้างการแสดงผลก่อนหน้านี้ โดยปกติหากไม่มีการระบุจะมีค่าเป็น `False`

**ตัวอย่าง** 1.3.2 กำหนดให้ตัวแปร 3 ตัวมีค่าดังนี้

In [ ]:
x1=10
x2=100
x3=1000

จงบอกคำสั่งที่แสดงผลค่าตัวแปรให้มีรูปแบบในแต่ละข้อต่อไปนี้

1.
```
10 100 1000
```

In [ ]:
print(x1,x2,x3)

2.
```
10  100  1000
```

In [ ]:
print(x1,'',x2,'',x3)
print(x1,"",x2,"",x3)

3.
```
10 --> 100 --> 1000 -->
```

In [ ]:
print(x1,'-->',x2,'-->',x3,'-->')

4.
```
10   -->
100  -->
1000 -->
```

In [ ]:
print(x1,'  -->')
print(x2,' -->')
print(x3,'-->')

นอกจากนี้ ผู้ใช้งานสามารถกำหนดรูปแบบค่าของตัวแปรทีต้องการแสดงผลให้เป็นไปตามความต้องการได้ตามประเภทของตัวแปรที่ระบุได้ ไม่ว่าตัวแปรนั้นจะเป็นจำนวนเต็ม จำนวนจริง หรือ สายอักขระ การกำหนดรูปแบบแสดงผลมีหลายรูปแบบ ในบทนี้จะแนะนำ 3 รูปแบบ ดังนี้

### การแสดงผลโดยการใช้ตัวดำเนินการ `%`
เป็นการกำหนดรูปแบบการแสดงผลแบบเดิม(คล้ายภาษา C)โดยมีรูปแบบดังนี้
```
print('Some string ... %[width][.precision]type'%(var))
```
เมื่อ

`width` เป็นจำนวนความยาวของอักขระที่ต้องการแสดงผล

`precision` เป็นจำนวนตำแหน่งทศนิยม (ถ้ามี)

`type` เป็นประเภทของรูปแบบ ได้แก่
- `d` แสดงผลเป็นจำนวนเต็ม
- `f` แสดงผลเป็นจำนวนจริงแบบทศนิยมจุดลอย(floating point)
- `e` แสดงผลแบบสัญกรณ์ทางวิทยาศาสตร์
- `s` แสดงผลแบบสายอักขระ

`var` เป็นชื่อตัวแปรที่ต้องการแสดงค่า

**ตัวอย่าง 1.3.3** กำหนดให้ค่าของตัวแปรเป็นดังนี้

In [26]:
person='Leonhard Euler'
birth_year=1707
euler_const = 2.718281828459

In [27]:
print('Hello %s Hi %d and %.5f'%(person,birth_year,euler_const))

Hello Leonhard Euler Hi 1707 and 2.71828


จงแสดงข้อความ

```Leonhard Euler was born in 1707. He is the mathematician who presented the Euler constant e = 2.71828```

ด้วยคำสั่ง `print` และใช้ตัวดำเนินการ `%` เพื่อนำค่าตัวแปรที่กำหนดให้มาแสดงในข้อความที่กำหนด

In [28]:
print('%s was born in %d. He is the mathematician who presented the Euler constant e = %.5f'%(person,birth_year,euler_const))

Leonhard Euler was born in 1707. He is the mathematician who presented the Euler constant e = 2.71828


In [29]:
print('%s was born in %d. He is the mathematician who presented the Euler constant e = %15.5f'%(person,birth_year,euler_const))

Leonhard Euler was born in 1707. He is the mathematician who presented the Euler constant e =         2.71828


### การแสดงผลโดยการใช้ `f-strings`
รูปแบบการใช้งาน
```
print(f'...Some strings...{var1:format1}...Some strings {var2:format2}...')
```
หรือ
```
print(f"...Some strings...{var1:format1}...Some strings {var2:format2}...")
```
เมื่อ `var1`, `var2` เป็นชื่อตัวแปร และ `format1`, `format2` เป็นรูปแบบที่ต้องการแสดงผลที่กำหนดเหมือนกับกรณีการใช้ `%` แต่ไม่ต้องใส่เครื่องหมาย `%`

11**ตัวอย่าง 1.3.4** จงแสดงข้อความเหมือนในตัวอย่าง 1.3.3 โดยใช้ `f-strings`

In [30]:
print(f'{person:s} was born in {birth_year:d}. He is the mathematician who presented the Euler constant e = {euler_const:.5f}')

Leonhard Euler was born in 1707. He is the mathematician who presented the Euler constant e = 2.71828


In [31]:
print(f'{person:20s} was born in {birth_year:6d}. He is the mathematician who presented the Euler constant e = {euler_const:.5f}')

Leonhard Euler       was born in   1707. He is the mathematician who presented the Euler constant e = 2.71828


### การแสดงผลโดยการใช้ `str.format()`
รูปแบบการใช้งาน
```
print('Some strings {:format1} some strings {:format2} ....'.format(var1,var2,...))
```
หรือ
```
print('Some strings {var1:format1} some strings {var2:format2} ....'.format(var1=value1,var2=value2,...))
```
เมื่อ `var1`, `var2` เป็นชื่อตัวแปร และ `format1`, `format2` เป็นรูปแบบที่ต้องการแสดงผลที่กำหนดเหมือนกับกรณีการใช้ `%` แต่ไม่ต้องใส่เครื่องหมาย `%`

**ตัวอย่าง 1.3.5** จงแสดงข้อความเหมือนในตัวอย่าง 1.3.3 โดยใช้ `str.format()`

In [32]:
print('{:s} was born in {:d}. He is the mathematician who presented the Euler constant e = {:.5f}'.format(person,birth_year,euler_const))

Leonhard Euler was born in 1707. He is the mathematician who presented the Euler constant e = 2.71828


In [33]:
print('{:20s} was born in {:6d}. He is the mathematician who presented the Euler constant e = {:10.5f}'.format(person,birth_year,euler_const))

Leonhard Euler       was born in   1707. He is the mathematician who presented the Euler constant e =    2.71828


## 1.3.3 การเปิดและปิดไฟล์
การเปิดไฟล์จะใช้คำสั่งดังนี้

```
fileID = open(Filename,mod)
```

เมื่อ
`Filename` เป็นตัวแปรแบบสตริงที่เป็นชื่อไฟล์ที่ต้องการเปิด(พร้อมนามสกุลของไฟล์)

`mode` เป็นลักษณะการเปิดไฟล์ ซึ่งมีดังนี้

- `'r'` เป็นการเปิดไฟล์เพื่ออ่านอย่างเดียว ถ้าไม่มีไฟล์ปรากฏอยู่จะเกิดข้อผิดพลาด(error)

- `'a'` เป็นการเปิดไฟล์โดยที่ ถ้า ไฟล์ที่จะเปิดนั้นยังไม่ปรากฏอยู่ก็สร้างไฟล์นั้นขึ้นมาให้

- `'w'` เป็นการเปิดไฟล์ที่ผู้ใช้งานสามารถเขียนข้อมูลลงไปในไฟล์ที่เปิดอยู่ได้ หากไฟล์ที่เปิดไม่ปรากฏอยู่ก็จะสร้างไฟล์นั้นๆ ขึ้นมาแต่ถ้าไฟล์นั้นมีอยู่แล้ว ข้อมูลในไฟล์จะถูกลบออกทั้งหมดก่อนมีการเขียนลงไปใหม่

- `'x'` เป็นการสร้างไฟล์เฉพาะ ถ้ามีไฟล์อยู่แล้วก็จะเกิดข้อผิดพลาดเกิดขึ้น

นอกจากนี้ ผู้ใช้งานยังสามารถระบุประเภทการเขียนข้อมูลลงไปในไฟล์ได้ว่าจะต้องการเขียนไฟล์แบบ
- ข้อความธรรมดา(text mode) ด้วยการระบุ `t`  หรือ
- แบบภาษาเครื่อง(binary mode) `b` (ไฟล์ประเภทรูปภาพ)

ต่อท้าย `mode` ได้

เมื่อทำการเขียนข้อมูลเสร็จแล้ว ผู้ใช้งานสามารถปิดไฟล์ด้วยคำสั่ง `close` ดังนี้
```
fileID.close()
```

In [39]:
filenew = open("banana.txt","a")

**ตัวอย่าง 1.3.6**
จงเขียนคำสั่งไพทอนเพื่อให้โปรแกรมทำงานดังต่อไปนี้
1. เก็บชื่อและนามสกุลไว้ในตัวแปรสายอักขระ A1
2. เก็บลำดับเลขที่สมัครในโครงการฯไว้ในตัวแปรจำนวนเต็ม A2
3. เก็บจำนวนคะแนนที่ได้จากการเรียน Codecombat (ที่เป็น % จากคะแนนเต็ม 35%)เป็นตัวแปรจำนวนทศนิยม A3
4. ตั้งชื่อและเปิดไฟล์ 'EsarnCoding.txt'

เมื่อเปิดไฟล์สำเร็จ ให้ทำการเขียนข้อมูลต่อไปนี้ลงในไฟล์ดังกล่าว
1. เขียนข้อความ “This is my personal data in E-sarn Thailand Coding and AI Project”
2. เขียนข้อความ “My name is ”  ตามด้วยข้อมูลที่เก็บไว้ในตัวแปร A1
3. เขียนข้อความ “My registered ID is ” * ตามด้วยข้อมูลที่เก็บไว้ในตัวแปร A2
4. เขียนข้อความ “My Codecombat score is” ตามด้วยข้อมูลที่เก็บไว้ในตัวแปร A3 โดยแสดงเลขทศนิยม 5 ตำแหน่ง
5. แสดงค่าประโยคข้างต้นให้อยู่คนละบรรทัดกัน
6. ปิดไฟล์และตรวจสอบว่าข้อมูลต่างๆ ที่เขียนลงไปในไฟล์ที่กำหนดถูกต้องหรือไม่

In [51]:
A1 = "Natthasit Wongprang"
A2 = 69
A3 = 420
fileID = open("Natthasit Test","wt")
print(" This is my personal data in E-sarn Thailand Coding and AI Project",file = fileID)
print(" My name is {:s}".format(A1),file = fileID)
print(" My registered ID is {:d}".format(A2),file = fileID)
print(" My Codecombat score is {:.5f}".format(A3),file = fileID)
fileID.close()

In [41]:
A1='Weerachai Sarakorn'
A2=1
A3= 29.0
fileID=open('EsarnCoding.txt','wt')
print('This is my personal data in E-sarn Thailand Coding and AI Project',file=fileID)
print('My name is {:s}'.format(A1),file=fileID)
print('My registered ID is {:d}'.format(A2),file=fileID)
print('My Codecombat score is {:.5f}'.format(A3),file=fileID)
fileID.close()

# 1.4 คำสั่งและตัวดำเนินการต่างๆ ที่เกี่ยวกับข้อมูลแบบพื้นฐาน

## 1.4.1 การเปลี่ยนประเภทการจัดเก็บของตัวแปรพื้นฐาน
หากผู้ใช้งานมีความจำเป็นที่จะเปลี่ยนจะประเภทการจัดเก็บของตัวแปรพื้นฐานที่กำหนดให้จัดเก็บเป็นตัวแปรพื้นฐานประเภทอื่น ก็สามารถทำได้ ตัวอย่างคำสั่งการเปลี่ยนประเภทการจัดเก็บของตัวแปรที่สำคัญมีดังนี้

1. `int` เป็นคำสั่งที่ใช้แปลงค่าตัวแปรและจัดเก็บให้เป็นตัวแปรจำนวนเต็ม
2. `float` เป็นคำสั่งที่ใช้แปลงค่าตัวแปรและจัดเก็บให้เป็นตัวแปรจำนวนทศนิยม
3. `str` เป็นคำสั่งที่ใช้แปลงค่าตัวแปรและจัดเก็บให้เป็นตัวแปรสายอักขระ
4. `bool` เป็นคำสั่งที่ให้แปลงค่าตัวแปรและจัดเก็บให้เป็นตัวแปรบูลีน สำหรับตัวแปรที่ไม่ได้จัดเก็บเป็นตัวแปรบูลีน เมื่อใช้คำสั่งนี้จะได้ค่าตัวแปรเป็นจริง หากตัวแปรนั้นเป็นตัวแปรบูลีน จะได้ค่าความจริงตามที่จัดเก็บไว้ก่อนหน้านี้

**ตัวอย่าง 1.4.1** กำหนดค่าตัวแปรดังต่อไปนี้

In [35]:
a=100.
b=100.99
c=100
d='101'
e=True
f=False

1. จงแปลงค่าตัวแปร `a`,`b` และ `d`ให้เป็นตัวแปรจำนวนเต็มโดยจัดเก็บไว้ในตัวแปร `inta`,`intb` และ `intd` ตามลำดับ จากนั้นแสดงค่าตัวแปรและประเภทของตัวแปรใหม่ทั้งสาม

In [36]:
inta=int(a)
print(inta)
print(type(inta))

100
<class 'int'>


In [37]:
intb=int(b)
print(intb)
print(type(intb))

100
<class 'int'>


In [38]:
intd=int(d)
print(intd)
print(type(intd))

101
<class 'int'>


2. จงแปลงค่าตัวแปร `c` ให้เป็นตัวแปรจำนวนทศนิยมโดยจัดเก็บไว้ในตัวแปร `floatc`แสดงค่าตัวแปรนี้และแสดงประเภทของตัวแปรนี้

In [ ]:
floatc=float(c)
print(floatc)
print(type(floatc))

3. จงแปลงค่าตัวแปร `a`, `c` ให้เป็นตัวแปรแบบสายอักขระและจัดเก็บไว้ในตัวแปร `stra` และ `strc` ตามลำดับ จากนั้นแสงค่าตัวแปรและประเภทของตัวแปรใหม่ทั้งสอง

In [ ]:
stra=str(a)
strc=str(c)
print(stra,strc)
print(type(stra),type(strc))

4. จงใช้คำสั่ง `bool` สำหรับตัวแปรทั้งหมดและแสดงผลที่ได้ พร้อมตั้งข้อสังเกตุกับค่าที่ได้

In [ ]:
print(bool(a))
print(bool(b))
print(bool(c))
print(bool(d))
print(bool(e))
print(bool(f))

## 1.4.2 ตัวดำเนินการเกี่ยวกับตัวแปรประเภทจำนวนเต็มและตัวแปรประเภททศนิยม


ตัวดำเนินการที่สำคัญสำหรับพร้อมสัญลักษณ์ แสดงดังตารางต่อไปนี้

| **ประเภทของการดำเนินการ**  | **สัญลักษณ์** |
|-----------------------------|--------|
| การบวก                      | `+`    |
| การลบ                       | `-`    |
| การคูณ                       | `*`    |
| การหาร                      | `/`    |
| การยกกำลัง                   | `**`   |
| การหารแบบปัดเศษให้เป็นจำนวนเต็ม | `//`   |
| การหารหาเศษเหลือ             | `%`    |




**ตัวอย่าง1.4.2** จงหาค่าที่กำหนดให้ต่อไปนี้

1. $-1+\frac{2}{3+0.45}-\frac{5^6+6^7}{(8+9(10))^2}$

In [ ]:
-1+2/(3+0.45)-(5**6+6**7)/(8+9*10)**2

2. $z=1-xy+y^2+\frac{x}{-1+x(x^2-y^{\frac{2}{3}})}$ เมื่อ $x=-1,y=3$

In [ ]:
x=-1
y=3
z=1-x*y+y**2+x/(-1+x*(x**2-y**(2/3)))
print(z)

3. จงเขียนคำสั่งเพื่อรับค่าจำนวนเต็ม 3 จำนวนจากแป้นพิมพ์(บรรทัดละจำนวน) เก็บในตัวแปร $h, m$ และ $s$ ซึ่งแทนจำนวน ชั่วโมง นาที และ วินาที
จากนั้น คำนวณจำนวนวินาทีรวมจาก $h, m$ และ $s$ แล้วแสดงผลจำนวนวินาทีรวมทั้งหมดที่คำนวณได้

In [ ]:
h=int(input('Input number of hours = '))
m=int(input('Input number of minutes = '))
s=int(input('Input number of seconds = '))
# Ttotal is the total of times in seconds
Ttotal = s+m*60+h*3600
print('The total times is {:d} seconds.'.format(Ttotal))

4. หาร $20$ ด้วย $q$ เมื่ $q=2,3,7,-7$ แบบปัดเศษให้เป็นจำนวนเต็ม

In [ ]:
20//2

In [ ]:
20//3

In [ ]:
20//7

In [ ]:
20//-7

5. หาค่าและแสดงผลเศษเหลือ $r$ ที่เกิดจาการหาร $p$ ด้วย $q$ เมื่อ $q\neq 0$ โดยทำการป้อนค่า $p$ และ $q$ จากแป้นพิมพ์

In [ ]:
p=int(input('Input p = '))
q=int(input('Input q = '))
r=p%q
print('The remainder r = {:d}'.format(r))

## 1.4.3 คำสั่งพื้นฐานเกี่ยวกับตัวแปรสตริง
คำสั่งต่างๆ ที่สำคัญเกี่ยวกับตัวแปรประเภทสตริงที่จะแนะนำในบทนี้ ได้แก่
1. `len(var)` ใช้หาความยาวของตัวแปรประเภทสตริง `var`
2. `var.replace(s1,s2)` การแทนที่กลุ่มอักขระเดิม `s1` ในตัวแปร `var` ด้วยกลุ่มอักขระใหม่ `s2`
3. `var.split(" ")` การแยกกลุ่มข้อความออกจากกันด้วยช่องว่าง` ` (หากต้องการแยกข้อความด้วยอักขระอื่น ให้แทนที่ช่องว่างด้วยอักขระนั้นๆ เช่น `,`,`.` เป็นต้น
4. `var.capitalize()` เปลี่ยนตัวอักษรภาษาอังกฤษตัวแรกใน `var' ให้เป็นตัวอักษรพิมพ์ใหญ่
5. `var.lower()`เปลี่ยนตัวอักษรภาษาอังกฤษในตัวแปรสายอักขระ `var` ให้เป็นตัวพิมพ์เล็ก
6. `var.upper()` เปลี่ยนตัวอักษรภาษาอังกฤษในตัวแปรสายอักขระ `var` ให้เป็นตัวพิมพ์ใหญ่
เป็นต้น

**ตัวอย่าง1.4.3** กำหนดตัวแปรดังต่อไปนี้

In [ ]:
s1='data scientist and ai creator are the most favourite job in the present.'

1. จงหาจำนวนอักขระในตัวแปรที่กำหนดให้

In [ ]:
len(s1)

2. จงแทนที่ตัวอักษร `a` ด้วยตัวอักษร `A` ในสตริงของตัวแปรที่กำหนดให้

In [ ]:
s2 = s1.replace('a','A')
print(s2)

3. จงแยกข้อความในตัวแปรที่กำหนดให้โดยใช้ช่องว่างเป็นตัวกำหนด

In [ ]:
s3=s1.split(" ")
print(s3)

In [ ]:
len(s3)

In [ ]:
s4=s1.split(".")
print(s4)

In [ ]:
len(s4)

4. จงเปลี่ยนข้อความในตัวแปรที่กำหนด ให้เป็นตัวอักษรตัวเล็กทั้งหมด

In [ ]:
s5=s1.lower()
print(s5)

5. จงเปลี่ยนข้อความในตัวแปรที่กำหนด ให้เป็นตัวอักษรตัวใหญ่ทั้งหมด

In [ ]:
s6=s1.upper()
print(s6)

## 1.4.4 ตัวดำเนินการเกี่ยวกับตัวแปรประเภทสตริง
สำหรับตัวดำเนินการเกี่ยวกับตัวแปรประเภทสตริงจะเป็นการนำค่าตัวแปรสตริงมาเรียงต่อกัน(concatenation)ซึ่งการดำเนินการดังกล่าวสามาถทำได้โดยใช้เครื่องหมาย `+`

**ตัวอย่าง1.4.4** กำหนดตัวแปรเป็นดังนี้

In [ ]:
s1='data scientist'
s2='and'
s3='ai creator'
s4='the most favourite job'
s5='in the present'

1. จงสร้างกลุ่มข้อความ `'data scientist and ai creator'` จากตัวแปรบางตัวแปรที่กำหนดให้และประยุกต์ใช้สตริงอื่นๆ เพิ่มเติม

In [ ]:
s1+' '+s2+' '+s3

2. จงสร้างข้อความ `'data scientist and ai creator are the most favourite job in the present.:)'` จากตัวแปรที่กำหนดให้ทั้งหมดและประยุกต์ใช้สตริงอื่นๆ เพิ่มเติม

In [ ]:
s1+' '+s2+' '+s3+' are '+s4+' '+s5+'.:)'

## 1.4.5 ตัวดำเนินการเกี่ยวกับตัวแปรบูลีน
ตัวดำเนินการเกี่ยวกับตัวแปรบูลีนประกอบด้วย 3 ตัวดำเนินการดังนี้
1. ตัวดำเนินการ นิเสธ(Not)สัญลักษณ์ทางคณิตศาสตร์คือ ~ ใช้คำสั่ง `not` หน้าตัวแปรที่ต้องการโดยต้องเว้นวรรคกับตัวแปร
2. ตัวดำเนินการ และ(and) สัญลักษณ์ทางคณิตศาสตร์คือ $\wedge$ ใช้คำสั่ง`and` เชื่อมระหว่างสองตัวแปรโดยต้องเว้นวรรคกับตัวแปร
3. ตัวดำเนินการ หรือ(or) สัญลักษณ์ทางคณิตศาสตร์คือ $\vee$ ใช้คำสั่ง `or` เชื่อมระหว่างสองตัวแปรโดยต้องเว้นวรรคกับตัวแปร
**หมายเหตุ:** หากใช้ตัวดำเนินการโดยไม่เว้นวรรคให้ใส่ `()` คร่อมตัวแปรแทน

**ตัวอย่าง1.4.5** กำหนดตัวแปรดังนี้

In [ ]:
b1=True
b2=False
b3=True

จงหาค่าดังต่อไปนี้

1. ~$b1$

In [ ]:
not b1

In [ ]:
not(b1)

2. $b1 \wedge b2$

In [ ]:
b1 and b2

3. $b2 \vee b3$

In [ ]:
(b2)or(b3)

4. $b2\vee$ ~$(b1 \wedge b3)$

In [ ]:
b2 or not(b1 and b3)

## 1.4.6 การเปรียบเทียบตัวแปร
การเปรียบเทียบตัวแปรแบบต่างๆ แสดงดังนี้

| **ลักษณะการเปรียบเทียบ** | **สัญลักษณ์** |
|-----------------------|------------|
| การเท่ากัน              | `==`       |
| การไม่เท่ากัน            | `!=`       |
| น้อยกว่า                | `<`        |
| น้อยกว่าหรือเท่ากับ        | `<=`       |
| มากกว่า                | `>`        |
| มากกว่าหรือเท่ากับ        | `>=`       |


**ตัวอย่าง1.4.6** กำหนดค่าตัวแปรดังนี้

In [ ]:
a= -9
b= 7

จงหาค่าความจริงจากการเปรียบเทียบค่าของสองตัวแปรในกรณีต่างๆ ตามตารางข้างต้น

In [ ]:
a==b

In [ ]:
a!=b

In [ ]:
a<b

In [ ]:
a<=b

In [ ]:
a>b

In [ ]:
a>=b

---

# เอกสารอ้างอิง
1. Python Language. https://www.python.org
2. Sowmya Krishnan. Data Structures in Python-A Brief Introduction. https://images.app.goo.gl/aTn7VP5tp3N2nhLG6
3. https://docs.python.org/3/tutorial/inputoutput.html
4. กิตติภณ พละการ, กิตติภพ พละการ, สมชาย ประสิทธิ์จูตระกูล และ สุกรี สินธุภิญโญ. ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย. Python 101. https://www.cp.eng.chula.ac.th/books/python101/
5. เดช ธรรมศิริ. รายวิชา 3602801 การเขียนโปรแกรมคอมพิวเตอร์ทางธุรกิจ. มหาวิทยาลัยราชภัฏนครปฐม. http://courseware.npru.ac.th/admin/files/20210907110003_65235a3b992bf4f7d36b7e3cb735f37c.pdf

<img src = 'https://drive.google.com/uc?id=18qUXmnQK3FIPfMCm8m0aKf1Saam6ezdJ'>

<img src = 'https://drive.google.com/uc?id=192V5NZG8GXDFzYQIxTRJCSmiBUkc2xys'>